name: main.yml
on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup C++ env
              uses: actions/setup-cpp@v2
            - name: Build
              run: make